<?php
namespace PhalconRest\Authentication;

/**
 * what should the adapter be forced to provide?
 * 
 * @author jjenkins
 *        
 */
interface AdapterInterface
{

    /**
     * store any error messages generated by the adapter during the course of attempting to log in
     *
     * @var string
     */
    public $errorMessage;

    /**
     * each adapter mush provide a way to authenticate a user
     * @param string $userName
     * @param string $password
     * @return boolean
     */
    function authenticate($userName, $password);
}
